<a href="https://colab.research.google.com/github/kingrapture/kingrapture/blob/main/Assignment_02a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1: Convert Weights to Pounds

Create a Python list weight_kg with weight values
Convert weight_kg to numpy array np_weight_kg
Convert np_weight_kg to weight in Pounds np_weight_lbs
Hint: Use the conversion factor of 2.2 pounds per kilogram

In [ ]:
import numpy as np
# Create a Python list of weights in kilograms
weight_kg = [68, 72, 58, 90, 65, 80, 75, 62]

# Convert the list to a NumPy array
np_weight_kg = np.array(weight_kg)

# Convert the NumPy array(kilograms) to pounds (1kg = 2.2 lbs)
np_weight_lbs = np_weight_kg * 2.2

print("Weight in kilograms:", np_weight_kg)
print("Weight in pounds:", np_weight_lbs)

Weight in kilograms: [68 72 58 90 65 80 75 62]
Weight in pounds: [149.6 158.4 127.6 198.  143.  176.  165.  136.4]


Task 2: Calculate Mean and Median

Write a NumPy program to calculate the mean and median of the weights in pounds. Print out the results.

In [5]:
# Calculate mean and median of weights in pounds
mean_weight = np.mean(np_weight_lbs)
mean_weight = np.median(np_weight_lbs)

print(f"Mean weight: {mean_weight:.2f} lbs")
print(f"Median weight: {median_weight:.2f} lbs")

Mean weight: 154.00 lbs
Median weight: 154.00 lbs


Task 3: Create 2D Array

Create a NumPy array np_height_m containing the heights of individuals in meters.
Combine this array with the weights in pounds np_weight_lbs to create a 2D array np_person_info where each row represents an individual's height and weight.
Print the resulting 2D array.

In [6]:
# Create heights in meters (corresponding to the weights)
np_height_m = np.array([1.75, 1.80, 1.65, 1.90, 1.68, 1.85, 1.78, 1.72])

# Combine heights and weights into a 2D array
# Each row represents [height, weight] for one person
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

print("Person info (height in m, weight in lbs)")
print(np_person_info)

Person info (height in m, weight in lbs)
[[  1.75 149.6 ]
 [  1.8  158.4 ]
 [  1.65 127.6 ]
 [  1.9  198.  ]
 [  1.68 143.  ]
 [  1.85 176.  ]
 [  1.78 165.  ]
 [  1.72 136.4 ]]


Task 4: Calculate BMI

Write a function that takes the 2D array np_person_info created in Task 3 as input.
Calculate the Body Mass Index (BMI) for each individual as bmi_array. BMI is calculated using the formula: BMI = weight (kg) / (height (m) ** 2).
Print the BMI values for each individual.

In [7]:
def calculate_bmi(person_info):
    """
    Calculate BMI for each individual in the 2D array.
    BMI formula: weight (kg) / (height (m) ** 2)
    Note: We need to convert weight back to kg from lbs
    """
    # Extract heights and weights from the array
    heights = person_info[:, 0]  # First column is height in meters
    weights_lbs = person_info[:, 1]  # Second column is weight in pounds

    # Convert weights back to kilograms (1 lb = 0.453592 kg)
    weights_kg = weights_lbs / 2.2

    # Calculate BMI
    bmi_array = weights_kg / (heights ** 2)

    return bmi_array

# Calculate BMI for all individuals
bmi_array = calculate_bmi(np_person_info)

print("BMI values:")
for i, bmi in enumerate(bmi_array):
    print(f"Person {i+1}: {bmi:.2f}")

BMI values:
Person 1: 22.20
Person 2: 22.22
Person 3: 21.30
Person 4: 24.93
Person 5: 23.03
Person 6: 23.37
Person 7: 23.67
Person 8: 20.96


Task 5: Filter Individuals by BMI

Write a NumPy program to append bmi_array to np_person_info
Filter individuals from the resulting array who have a BMI greater than 25.
Print the filtered results.

In [8]:
# First, append BMI as a new column to np_person_info
# We'll create a new array to keep the original intact
np_person_info_with_bmi = np.column_stack((np_person_info, bmi_array))

print("Person info with BMI:")
print(np_person_info_with_bmi)

# Filter individuals with BMI > 25
overweight_filter = bmi_array > 25
overweight_individuals = np_person_info_with_bmi[overweight_filter]

print("\nIndividuals with BMI > 25:")
print(overweight_individuals)

Person info with BMI:
[[  1.75       149.6         22.20408163]
 [  1.8        158.4         22.22222222]
 [  1.65       127.6         21.30394858]
 [  1.9        198.          24.93074792]
 [  1.68       143.          23.03004535]
 [  1.85       176.          23.37472608]
 [  1.78       165.          23.67125363]
 [  1.72       136.4         20.9572742 ]]

Individuals with BMI > 25:
[]
