<a href="https://colab.research.google.com/github/kingrapture/kingrapture/blob/main/Assignment_02a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1: Convert Weights to Pounds

Create a Python list weight_kg with weight values
Convert weight_kg to numpy array np_weight_kg
Convert np_weight_kg to weight in Pounds np_weight_lbs
Hint: Use the conversion factor of 2.2 pounds per kilogram

In [2]:
import numpy as np
import pandas as pd
# Task 1: Convert Weights to Pounds

# Create a standard Python list containing several weight values in kilograms (kg).
weight_kg = [72, 85, 68, 91, 78, 82, 65, 88, 76, 94]
print(f"Original Python list (weights in kg): {weight_kg}")

# Convert the Python list 'weight_kg' into a NumPy array called 'np_weight_kg'.
# NumPy arrays are more efficient for numerical operations than standard Python lists.
np_weight_kg = np.array(weight_kg)
print(f"NumPy array (weights in kg): {np_weight_kg}")

# Define the conversion factor from kilograms to pounds.
kg_to_lbs_factor = 2.2

# Convert the weights from kilograms to pounds.
# We multiply the entire NumPy array 'np_weight_kg' by the conversion factor.
# This is a key feature of NumPy called vectorization, where an operation is applied
# to all elements of an array at once, which is highly efficient.
np_weight_lbs = np_weight_kg * kg_to_lbs_factor

# Print the resulting NumPy array containing weights in pounds (lbs).
# The output will show each weight from the original array converted to pounds.
print(f"NumPy array (weights in lbs): {np_weight_lbs}")

Original Python list (weights in kg): [72, 85, 68, 91, 78, 82, 65, 88, 76, 94]
NumPy array (weights in kg): [72 85 68 91 78 82 65 88 76 94]
NumPy array (weights in lbs): [158.4 187.  149.6 200.2 171.6 180.4 143.  193.6 167.2 206.8]


Task 2: Calculate Mean and Median

Write a NumPy program to calculate the mean and median of the weights in pounds. Print out the results.

In [3]:
# Calculate mean and median of weights in pounds
mean_weight = np.mean(np_weight_lbs)
median_weight = np.median(np_weight_lbs)

print(f"Mean weight: {mean_weight:.2f} lbs")
print(f"Median weight: {median_weight:.2f} lbs")

Mean weight: 175.78 lbs
Median weight: 176.00 lbs


In [ ]:
# Task 2: Calculate Mean and Median

# Calculate the mean (average) of the weights in pounds using NumPy's mean() function.
# This function sums all the elements in the array and divides by the number of elements.
mean_weight_lbs = np.mean(np_weight_lbs)

# Calculate the median of the weights in pounds using NumPy's median() function.
# The median is the value separating the higher half from the lower half of a data sample.
# It is often a better measure of central tendency than the mean for skewed data.
median_weight_lbs = np.median(np_weight_lbs)

# Print the calculated mean and median values with descriptive labels.
# We use an f-string to format the output nicely, rounding the results to two decimal places.
print(f"Mean weight: {mean_weight_lbs:.2f} lbs")
print(f"Median weight: {median_weight_lbs:.2f} lbs")

Mean weight: 175.78 lbs
Median weight: 176.00 lbs


Task 3: Create 2D Array

Create a NumPy array np_height_m containing the heights of individuals in meters.
Combine this array with the weights in pounds np_weight_lbs to create a 2D array np_person_info where each row represents an individual's height and weight.
Print the resulting 2D array.

In [14]:
# Create heights in meters (corresponding to the weights)
np_height_m = np.array([1.75, 1.80, 1.65, 1.90, 1.68, 1.85, 1.78, 1.72])

# Combine heights and weights into a 2D array
# Each row represents [height, weight] for one person
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

print("Person info (height in m, weight in lbs)")
print(np_person_info)

Person info (height in m, weight in lbs)
[[  1.75 158.4 ]
 [  1.8  187.  ]
 [  1.65 149.6 ]
 [  1.9  200.2 ]
 [  1.68 171.6 ]
 [  1.85 180.4 ]
 [  1.78 143.  ]
 [  1.72 193.6 ]]


In [16]:
# Task 3: Create 2D Array

# Create a NumPy array 'np_height_m' containing the heights of individuals in meters.
# The number of elements in this array must match the number of elements in the weight array
# to ensure they can be paired up correctly.
np_height_m = np.array([1.75, 1.80, 1.65, 1.90, 1.78, 1.83, 1.62, 1.88])

# Combine the height and weight arrays into a single 2D NumPy array.
# We use np.column_stack(), which takes a sequence of 1D arrays and stacks them as columns to make a single 2D array.
# The resulting shape will be (8, 2), representing 8 individuals with 2 data points each (height and weight).
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

# Print the resulting 2D array.
# Each inner list represents a row, with the first element being height in meters
# and the second element being weight in pounds.
print("2D Array of Person Info (Height (m), Weight (lbs)):")
print(np_person_info)

2D Array of Person Info (Height (m), Weight (lbs)):
[[  1.75 158.4 ]
 [  1.8  187.  ]
 [  1.65 149.6 ]
 [  1.9  200.2 ]
 [  1.78 171.6 ]
 [  1.83 180.4 ]
 [  1.62 143.  ]
 [  1.88 193.6 ]]


Task 4: Calculate BMI

Write a function that takes the 2D array np_person_info created in Task 3 as input.
Calculate the Body Mass Index (BMI) for each individual as bmi_array. BMI is calculated using the formula: BMI = weight (kg) / (height (m) ** 2).
Print the BMI values for each individual.

In [18]:
import numpy as np

# Heights (meters)
np_height_m = np.array([1.75, 1.80, 1.65, 1.90, 1.78, 1.83, 1.62, 1.88, 1.77, 1.95])

# Weights (kg → lbs, converted earlier in Task 1)
weight_kg = [72, 85, 68, 91, 78, 82, 65, 88, 76, 94]
np_weight_lbs = np.array(weight_kg) * 2.2

# Combine into 2D array: [height, weight]
np_person_info = np.column_stack((np_height_m, np_weight_lbs))

def calculate_bmi(person_info):
    heights = person_info[:, 0]  # first column: heights (meters)
    weights_lbs = person_info[:, 1]  # second column: weights (lbs)
    weights_kg = weights_lbs / 2.2  # convert lbs → kg
    bmi_array = weights_kg / (heights ** 2)  # apply BMI formula
    return bmi_array

bmi_array = calculate_bmi(np_person_info)

print("BMI values:")
for i, bmi in enumerate(bmi_array, 1):
    print(f"Person {i}: {bmi:.2f}")


BMI values:
Person 1: 23.51
Person 2: 26.23
Person 3: 24.98
Person 4: 25.21
Person 5: 24.62
Person 6: 24.49
Person 7: 24.77
Person 8: 24.90
Person 9: 24.26
Person 10: 24.72


In [ ]:
# Task 4: Calculate BMI

def calculate_bmi(person_info_array):
    """
    Calculates the BMI for each individual in a 2D NumPy array.

    Args:
        person_info_array: A 2D NumPy array where column 0 is height in meters
                           and column 1 is weight in pounds.

    Returns:
        A 1D NumPy array containing the calculated BMI for each individual.
    """
    # Extract the height in meters (first column, index 0) from the input array.
    heights_m = person_info_array[:, 0]

    # Extract the weight in pounds (second column, index 1) from the input array.
    weights_lbs = person_info_array[:, 1]

    # Convert weights from pounds back to kilograms for the BMI formula.
    # We divide by the same conversion factor used earlier.
    weights_kg = weights_lbs / 2.2

    # Calculate BMI using the formula: BMI = weight (kg) / (height (m) ** 2)
    # The operation is vectorized, calculating all BMIs at once.
    bmi_values = weights_kg / (heights_m ** 2)

    return bmi_values

# Call the function with our 'np_person_info' array to get the BMI for each person.
bmi_array = calculate_bmi(np_person_info)

# Print the resulting array of BMI values, rounded for readability.
print("Calculated BMI for each individual:")
print(np.round(bmi_array, 2))

Calculated BMI for each individual:
[23.51 26.23 24.98 25.21 24.62 24.49 24.77 24.9  24.26 24.72]


Task 5: Filter Individuals by BMI

Write a NumPy program to append bmi_array to np_person_info
Filter individuals from the resulting array who have a BMI greater than 25.
Print the filtered results.

In [20]:
# First, append BMI as a new column to np_person_info
# We'll create a new array to keep the original intact
np_person_info_with_bmi = np.column_stack((np_person_info, bmi_array))

print("Combined Array with Height, Weight and BMI:")
print("Person info with BMI:")
print(np_person_info_with_bmi)

# Filter individuals with BMI > 25
overweight_filter = bmi_array > 25
overweight_individuals = np_person_info_with_bmi[overweight_filter]

print("\nIndividuals with BMI > 25:")
print(overweight_individuals)

Combined Array with Height, Weight and BMI:
Person info with BMI:
[[  1.75       158.4         23.51020408]
 [  1.8        187.          26.2345679 ]
 [  1.65       149.6         24.97704316]
 [  1.9        200.2         25.20775623]
 [  1.78       171.6         24.61810377]
 [  1.83       180.4         24.48565201]
 [  1.62       143.          24.76756592]
 [  1.88       193.6         24.89814396]
 [  1.77       167.2         24.25867407]
 [  1.95       206.8         24.72057857]]

Individuals with BMI > 25:
[[  1.8        187.          26.2345679 ]
 [  1.9        200.2         25.20775623]]


In [19]:
# Task 5: Filter Individuals by BMI

# First, append the calculated 'bmi_array' as a new column to the 'np_person_info' array.
# We use np.column_stack() again to join the original 2D array with the 1D BMI array.
# The new array will have three columns: Height (m), Weight (lbs), and BMI.
np_person_info_with_bmi = np.column_stack((np_person_info, bmi_array))

print("Combined Array with Height, Weight, and BMI:")
print(np_person_info_with_bmi)
print("\n" + "="*50 + "\n") # Separator for clarity

# Create a boolean condition to filter for individuals with a BMI greater than 25.
# This expression 'np_person_info_with_bmi[:, 2] > 25' creates a boolean array (e.g., [False, True, True, ...])
# where 'True' corresponds to rows where the BMI (in the 3rd column, index 2) is over 25.
bmi_filter_condition = np_person_info_with_bmi[:, 2] > 25

# Use the boolean array to index the main array. This is called boolean or "mask" indexing.
# It returns a new array containing only the rows where the filter condition was True.
filtered_individuals = np_person_info_with_bmi[bmi_filter_condition]

# Print the final filtered results.
# This table shows only the data for individuals with a BMI > 25.
print("Filtered Individuals (BMI > 25):")
print("Columns: Height (m), Weight (lbs), BMI")
print(filtered_individuals)

Combined Array with Height, Weight, and BMI:
[[  1.75       158.4         23.51020408]
 [  1.8        187.          26.2345679 ]
 [  1.65       149.6         24.97704316]
 [  1.9        200.2         25.20775623]
 [  1.78       171.6         24.61810377]
 [  1.83       180.4         24.48565201]
 [  1.62       143.          24.76756592]
 [  1.88       193.6         24.89814396]
 [  1.77       167.2         24.25867407]
 [  1.95       206.8         24.72057857]]


Filtered Individuals (BMI > 25):
Columns: Height (m), Weight (lbs), BMI
[[  1.8        187.          26.2345679 ]
 [  1.9        200.2         25.20775623]]
